### ISSUE TITLE
Specification

### ISSUE THREAD

**Issue by happytm** [LibreSolar/BMS48V#3]
What are the specifications for this board? specially compared to [http://electrodacus.com/SBMS100/manual/SBMSmanual.pdf](url)

**Comment by martinjaeger** [comment]
Compared to the SBMS, this one has a more modular approach. The control PCB and the power PCB (Switch'N'Sense) are separated and it is not targeted only for solar applications. In addition to that, it can handle higher voltages and cell numbrrs.

**Comment by happytm** [comment]
Thank you very much.
